DROP TABLE VEHICLE;
DROP TABLE DIRECTION;
DROP TABLE STOPS;
DROP TABLE ROUTE_BY_STOPS;

CREATE TABLE VEHICLE
(
    ID_VEHICLE      NUMBER PRIMARY KEY NOT NULL UNIQUE,
    VEHICLE_NAME    VARCHAR(32)        NOT NULL,
    VEHICLE_NAME_EN VARCHAR(32)        NOT NULL
);

INSERT INTO VEHICLE
VALUES (0, 'АВТОБУС', 'BUS');
INSERT INTO VEHICLE
VALUES (1, 'ТРОЛЛЕЙБУС', 'TROLLEY');

CREATE TABLE DIRECTION
(
    ID_DIRECTION      NUMBER PRIMARY KEY NOT NULL UNIQUE,
    DIRECTION_TYPE    VARCHAR(32)        NOT NULL,
    DIRECTION_TYPE_EN VARCHAR(32)        NOT NULL
);

INSERT INTO DIRECTION
VALUES (1, 'ПРЯМОЕ', 'DIRECT');
INSERT INTO DIRECTION
VALUES (2, 'ОБРАТНОЕ', 'RETURN');

CREATE TABLE STOPS
(
    ID_STOP   NUMBER PRIMARY KEY NOT NULL UNIQUE,
    STOP_NAME VARCHAR(64)        NOT NULL,
    LATITUDE  NUMBER             NOT NULL,
    LONGITUDE NUMBER             NOT NULL
);

CREATE TABLE ROUTE_BY_STOPS
(
    ROUTE_NUMBER  NUMBER NOT NULL,
    ID_VEHICLE    NUMBER NOT NULL REFERENCES VEHICLE (ID_VEHICLE),
    ID_DIRECTION  NUMBER NOT NULL REFERENCES DIRECTION (ID_DIRECTION),
    STOP_NUMBER   NUMBER NOT NULL,
    ID_STOP       NUMBER NOT NULL REFERENCES STOPS (ID_STOP),
    DISTANCE_BACK NUMBER NOT NULL,
    PRIMARY KEY (ID_VEHICLE, ID_DIRECTION, ID_STOP)
);

CREATE TABLE TRACK
(
    ROUTE_NUMBER      NUMBER NOT NULL,
    ID_VEHICLE        NUMBER NOT NULL REFERENCES VEHICLE (ID_VEHICLE),
    STOP_TIME_REAL    DATE   NOT NULL,
    ID_DIRECTION      NUMBER NOT NULL REFERENCES DIRECTION (ID_DIRECTION),
    ID_STOP           NUMBER NOT NULL REFERENCES STOPS (ID_STOP),
    CARRIER_BOARD_NUM NUMBER NOT NULL,
    PRIMARY KEY (ID_VEHICLE, ID_DIRECTION, ID_STOP)
);